version: "3.7"

services:

  frontend:
    ports:
      - "88:80"
    restart: "no"
  identifier:
    ports:
      - "81:80"
    restart: "no"

  mocklogin:
    image: lblod/mock-login-service:0.7.0
    environment:
      GROUP_TYPE: "http://www.w3.org/ns/org#Organization"

  dispatcher:
    restart: "no"

  database:
    environment:
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_OUTGOING_SPARQL_QUERY_RESPONSES: "true"
      LOG_ACCESS_RIGHTS: "true"
    restart: "no"

  virtuoso:
    ports:
      - "8895:8890"
    restart: "no"

  migrations:
    restart: "no"

  cache:
    restart: "no"

  resource:
    restart: "no"
    
  form-data-management:
    restart: "no"
    
  subsidies-consumer:
    restart: "no"

  subsidy-applications-management:
    restart: "no"

  subsidy-application-flow-management:
    restart: "no"

  file:
    restart: "no"

  db-cleanup:
    restart: "no"