version: '3.7'

services:
  identifier:
    restart: "no"
    ports:
      - 80:80

  mocklogin:
    image: lblod/mock-login-service:0.3.1
    
  dispatcher:
    restart: "no"

  database:
    environment:
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_OUTGOING_SPARQL_QUERY_RESPONSES: "true"
      LOG_ACCESS_RIGHTS: "true"
    restart: "no"

  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"

  migrations:
    restart: "no"

  cache:
    restart: "no"

  resource:
    restart: "no"
    
  form-data-management:
    restart: "no"
    
  subsidies-consumer:
    restart: "no"
    