PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit:	<http://data.vlaanderen.be/ns/besluit#> 
PREFIX mu:	<http://mu.semte.ch/vocabularies/core/> 


INSERT {
  GRAPH ?g {
    ?bestuurseenheid skos:topConceptOf <http://lblod.data.gift/concept-schemes/7e2b965e-c824-474f-b5d5-b1c115740083> ;
                      skos:inScheme <http://lblod.data.gift/concept-schemes/7e2b965e-c824-474f-b5d5-b1c115740083> .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                      mu:uuid ?uuid .
    FILTER(?uuid IN (
      "19483103-318e-435a-aa37-45e485406ee9",  # Beveren-Kruibeke-Zwijndrecht (Gemeente)
      "1ca65d65-54ff-4b44-b750-bd70c91191af",  # Nazareth-De Pinte (Gemeente)
      "add1e4eb-9ec7-4ea6-af82-335aa76b7d48",  # Pajottegem (Gemeente)
      "b8bb293d-aa22-4b43-bda4-0b6af76e9493",  # Merelbeke-Melle (Gemeente)
      "fd41f573-7d9a-4d9f-b7d0-d5b6114d1622",  # Beveren-Kruibeke-Zwijndrecht (OCMW)
      "7d53f659-3a3b-44b1-9e77-3ea067678c0e",  # Nazareth-De Pinte (OCMW)
      "650378e7-1bee-4737-91ff-5b20ac4623cf",  # Pajottegem (OCMW)
      "5d94b2fd-60ee-4e56-a1f0-a586d596adf6"   # Merelbeke-Melle (OCMW)
    ))
  }
}